language: python
sudo: required
services:
    - docker
python:
    - 3.6
env:
    - DOCKERFILE=Dockerfile
before_install:
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt-get update
    - sudo apt-get -y install docker-ce
install:
    - docker build -t bannsec/frida-util -f $DOCKERFILE .
script:
    - docker run -it --rm --privileged --cap-add ALL -e TRAVIS_BRANCH=$TRAVIS_BRANCH bannsec/frida-util bash -c 'cd /opt/frida-util && pytest tests/linux && if [ ! -z "$COVERALLS_REPO_TOKEN" ]; then coveralls; fi'
